### ISSUE TITLE
Capturing a bust of images upon hardware trigger

### ISSUE THREAD

**Issue by aweitz** [TheImagingSource/IC-Imaging-Control-Samples#1]
Hi,

I would like to capture and save a finite number of frames at a specified frame rate when a physical trigger is received by the camera. For example, when a hardware trigger is received, 75 frames should be acquired at 25fps over 3 seconds. 

All I've been able to do with the library here is "turn on" the live stream when the hardware trigger is received (see code below). Is there no way to also return each frame by using GetImage, for example?

`import tisgrabber as IC`
`cam = IC.TIS_CAM()`
`cam.ShowDeviceSelectionDialog() # configure trigger, burst count, fps` 
`cam.StartLive(1) # livestream window opens, but displays nothing`
`# send physical trigger`
`# livestream window starts showing video, then stops after burst_count frames have been collected`

I am using the DFK 33UX273, Python 3.5, Windows 10.

Thanks.

**Comment by TIS-Stefan** [comment]
Hello,

This task takes some more time. Also I have not good idea, how to solve this with the tisgrabber DLL
I figured out last Thursday, how to make Pyhton Callbacks into a C DLL, which would be the correct start, but this is not published yet.

Since this is not an issue, but a support case, I would like you to come back at https://www.theimagingsource.com/support/contact/ to me.

Alternatively I have a free Windows software, that can do, what you want and that saves single images. 

Stefan
