### ISSUE TITLE
Activate/deactivate external trigger using python script

### ISSUE THREAD

**Issue by PVaddy13** [TheImagingSource/IC-Imaging-Control-Samples#67]
Hello,

While using IC Capture 2.5 software, I noticed an external trigger activated at the beginning of the video capture. I had to deactivate it every time before capturing a video. Also, I am trying to capture videos using Python (have not been successful yet). Does this external trigger get activated while using the camera with Python also? If yes, do you have any program/script to check/modify the external trigger status?

Thank you,
Chandra.

**Comment by PVaddy13** [comment]
Hello Stefan,

As you mentioned in the other thread, I am able to activate/deactivate the trigger using the properties tab in the camera selection window.

Thank you,
Chandra.

**Comment by TIS-Stefan** [comment]
​
    

			
In github beanwortet.

	
	

						

	
		
										
							On May 15, 2023 at 4:00 PM, TheImagingSource/IC-Imaging-Control-Samples wrote:
					
	
	
		
							
                    

	Closed #67 as completed.

—Reply to this email directly, view it on GitHub, or unsubscribe.You are receiving this because you commented.Message ID: ***@***.***>



                    
                
					
	

 

								

	
		
										
							On May 15, 2023 at 4:00 PM, TheImagingSource/IC-Imaging-Control-Samples wrote:
					
	
	
		
							
                    

	Hello Stefan,
As you mentioned in the other thread, I am able to activate/deactivate the trigger using the properties tab in the camera selection window.
Thank you,
Chandra.

—Reply to this email directly, view it on GitHub, or unsubscribe.You are receiving this because you commented.Message ID: ***@***.***>



                    
                
					
	

 

								

	
		
										
							On May 15, 2023 at 3:26 PM, TheImagingSource/IC-Imaging-Control-Samples wrote:
					
	
	
		
							
                    

	Hello Stefan,
I appreciate you are working on my other issue with AVI capture. As I mentioned, I am new to using TIS cameras, any industrial cameras for that matter. So I am trying to learn as much as possible as soon as possible :). Feel free to answer them at your convenience.
Thank you,
Chandra.

—Reply to this email directly, view it on GitHub, or unsubscribe.You are receiving this because you commented.Message ID: ***@***.***>



                    
                
					
	

 

					
	
					
	Was this message helpful?
	  Yes  
	  It was OK  
	  No  

		
			

		View and manage this ticket online:
		https://theimagingsource.deskpro.com/tickets/105938
	


 
The Imaging Source · https://theimagingsource.deskpro.com/
    GASOZXZ82XT8J5BA4HK



    ​

     

@media only screen {
  html {
    min-height: 100%;
    background: #f3f3f3;
  }
}
